# Generated by Django 3.2.5 on 2021-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='future_value',
            field=models.JSONField(default=''),
        ),
        migrations.DeleteModel(
            name='FutureValue',
        ),
    ]
