# Generated by Django 3.2.5 on 2021-07-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_calculation_future_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='future_value',
            field=models.JSONField(default=dict),
        ),
    ]
