# Generated by Django 3.2.5 on 2021-07-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calculation_future_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='future_value',
            new_name='data',
        ),
        migrations.AddField(
            model_name='calculation',
            name='NPV',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='rate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
